### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by vanderkoltadmin29** [parkerj/eduTrac-SIS#114]
Getting this error upon Installation (6.2.9)

 Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbs1274144.plugin' doesn't exist in /homepages/46/d858011460/htdocs/CWIS/Liten/Orm.php:247 Stack trace: #0 /homepages/46/d858011460/htdocs/CWIS/Liten/Orm.php(247): PDOStatement->execute(Array) #1 /homepages/46/d858011460/htdocs/CWIS/Liten/Orm.php(313): Liten\Orm->query('SELECT \n\t plugi...', Array) #2 /homepages/46/d858011460/htdocs/CWIS/app/src/Hooks.php(231): Liten\Orm->find(Object(Closure)) #3 /homepages/46/d858011460/htdocs/CWIS/app/functions/hook-function.php(83): app\src\Hooks->load_activated_plugins('/homepages/46/d...') #4 /homepages/46/d858011460/htdocs/CWIS/app/functions/hook-function.php(554): load_activated_plugins('/homepages/46/d...') #5 /homepages/46/d858011460/htdocs/CWIS/index.php(71): require('/homepages/46/d...') #6 {main} thrown in /homepages/46/d858011460/htdocs/CWIS/Liten/Orm.php on line 247

**Comment by vanderkoltadmin29** [comment]
I did get an error of 
ERROR 1171 (42000) at line 119: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
on registration, but under that, I was given a confirmation of installation. (SSH not browser)
